### ISSUE TITLE
"Application Error" on pw/5.4.4.2

### ISSUE THREAD

**Issue by aerickson** [koreader/kpvbooklet#39]
I'm getting an "Application Error" on a Paperwhite 1 (gen 5) running FW 5.4.4.2 when running the latest head code (0.6.6+).

It does look like it's a Java versioning issue.

```
140101:050315 cvm[15403]: java.lang.UnsupportedClassVersionError: com/github/chrox/kpvbooklet/KPVBooklet (Unsupported major.minor version 52.0)
```

Full log (after enabling usbnetwork and clicking on a PDF):
```
140101:050145 system: I usbnet:kh_msg::waiting for volumd . . .
140101:050147 system: I usbnet:kh_msg::reconfiguring usb0 interface
140101:050147 system: I usbnet:kh_msg::starting telnetd
140101:050147 system: I usbnet:kh_msg::starting sshd
140101:050147 dropbear[15979]: Running in background
140101:050150 powerd[1078]: I lipc:evts:name=charging, origin=com.lab126.powerd:Event sent
140101:050150 lipc-send-event[15984]: I lipc:evts:name=usbPlugIn, origin=com.lab126.hal:Event sent
140101:050150 g_ether gadget: high speed config #1: CDC Ethernet (ECM)
140101:050155 dropbear[15987]: Child connection from 192.168.15.1:50500
140101:050155 dropbear[15987]: Pubkey auth succeeded for 'root' with key sha1!! 70:c9:51:2f:61:50:6f:8e:9e:e2:f2:e9:13:b1:28:69:35:0f:5d:38 from 192.168.15.1:50500
140101:050155 dropbear[15987]: User root executing login shell
140101:050203 todo[1072]: I todo:ProcessingToDo:status=starting,reason=NetworkStartup:Started processing ToDo
140101:050203 cvm[15403]: I lipc:evts:name=credentialsInstalled, origin=com.lab126.DeviceAuthenticationService:Event sent
140101:050203 todo[1072]: W url_builder:GetURLWarning:reason=missingGlobalParameter,param=currentCountry:
140101:050203 todo[1072]: E todo_get_document:GetToDoFailed:reason=ensureConnectionFailed,error=5:
140101:050203 todo[1072]: E todo:ProcessingToDoFailed:reason=getDocumentFailedNullDocument,errno=0:Null ToDo document returned
140101:050304 cvm[15403]: W IndexerThread:Warning::Indexer low heap slowdown 1
140101:050305 powerd[1078]: I def:battinfo:cap=97%, mAh=1090mAh, volt=4187mV, current=208mA, temp=71F, bp=4187mV, lmd=1126mAh, cycl=0, cyct=0:
140101:050306 powerd[1078]: I lipc:evts:name=battLevelChanged, origin=com.lab126.powerd, fparam=97:Event sent
140101:050315 Xorg: I GestureEngine:perfScenario::Sending button 1 down 1388581395.046766
140101:050315 powerd[1078]: I lipc:evts:name=t1TimerReset, origin=com.lab126.powerd:Event sent
140101:050315 cvm[15403]: I def:print::perfScenario CVM posting MouseEvent[MousePressed] time=1388581395098
140101:050315 cvm[15403]: I def:print::
140101:050315 root: perfScenario CVM received X11 ButtonPress button=1 time=1388581395.098611
140101:050315 Xorg: I GestureEngine:perfScenario::Sending button 1 up 1388581395.170289
140101:050315 root: perfScenario CVM received X11 ButtonRelease button=1 time=1388581395.202139
140101:050315 cvm[15403]: I def:print::perfScenario CVM POINTER_CLICKED-gen btn=1  -> radius=2.0 time=1388581395204
140101:050315 cvm[15403]: I def:print::
140101:050315 cvm[15403]: I def:print::perfScenario CVM posting MouseEvent[MouseRelease] time=1388581395204
140101:050315 cvm[15403]: I def:print::
140101:050315 cvm[15403]: I def:print::perfScenario CVM posting MouseEvent[MouseClicked] time=1388581395205
140101:050315 cvm[15403]: I def:print::
140101:050315 appmgrd[1081]: I appmgr_registry:app_found_for_uri:lipc_app_id=com.github.koreader.kpvbooklet,executable=NONE:
140101:050315 appmgrd[1081]: I appmgr_history:FOUND_APP:lipcId=com.github.koreader.kpvbooklet:
140101:050315 appmgrd[1081]: E lipc:dbuserr:name=org.freedesktop.DBus.Error.ServiceUnknown:Receive Dbus error message (DBUS_MESSAGE_TYPE_ERROR): The name com.github.koreader.kpvbooklet was not provided by any .service files
140101:050315 appmgrd[1081]: E appmgr_lipc:lipc_set_prop_fail:lipc_status=3,app=com.github.koreader.kpvbooklet,property=go:send app command
140101:050315 appmgrd[1081]: W appmgr_history:unable_to_send_go:lipc_id=com.github.koreader.kpvbooklet,LipcStatus=3:Unable to send GO, re-loading
140101:050315 cvm[15403]: I BookletManager:StartingBooklet:booklet=com.github.koreader.kpvbooklet:
140101:050315 appmgrd[1081]: I appmgr_history:app_state_change:lipc_id=com.github.koreader.kpvbooklet,state=EXECUTED:
140101:050315 cvm[15403]: E BookletManager:BookletClassInitError:class=/opt/amazon/ebook/booklet/KPVBooklet.jar:
140101:050315 cvm[15403]: java.lang.UnsupportedClassVersionError: com/github/chrox/kpvbooklet/KPVBooklet (Unsupported major.minor version 52.0)
140101:050315 cvm[15403]: 	at java.lang.ClassLoader.defineClass0(Native Method)
140101:050315 cvm[15403]: 	at java.lang.ClassLoader.defineClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.security.SecureClassLoader.defineClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.net.URLClassLoader.defineClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.net.URLClassLoader.access$100(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.net.URLClassLoader$1.run(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.security.AccessController.doPrivileged(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.net.URLClassLoader.findClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at sun.misc.Launcher$AppClassLoader.findClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.lang.ClassLoader.loadClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.lang.ClassLoader.loadClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at java.lang.ClassLoader.loadClass(Compiled Method)(Unknown Source)
140101:050315 cvm[15403]: 	at com.amazon.kindle.restricted.booklet.impl.BookletManager.Tnb(aqc:827)
140101:050315 cvm[15403]: 	at com.amazon.kindle.restricted.booklet.impl.C.run(aqc:1537)
140101:050315 cvm[15403]: 	at com.amazon.ebook.util.b.a.run(ftf:252)
140101:050315 cvm[15403]: 	at java.lang.Thread.run(Unknown Source)
140101:050315 cvm[15403]: 	at java.lang.Thread.startup(Unknown Source)
140101:050315 appmgrd[1081]: I appmgr_lipc:set_appmgr_run_result:propName=runresult,buf=1:com.github.koreader.kpvbooklet:entry
140101:050315 appmgrd[1081]: I appmgr_history:app_state_change:lipc_id=com.github.koreader.kpvbooklet,state=REGISTERED:
140101:050315 cvm[15403]: I BookletManager:TerminatingBooklet:booklet=com.github.koreader.kpvbooklet:
140101:050315 pillow[15030]: I def:show-system-alert:id=appmgrAppFailedFatal, altId=appmgrAppFailedFatal, alertLogInfo=undefined:
140101:050315 appmgrd[1081]: E lipc:dbuserr:name=org.freedesktop.DBus.Error.ServiceUnknown:Receive Dbus error message (DBUS_MESSAGE_TYPE_ERROR): The name com.github.koreader.kpvbooklet was not provided by any .service files
140101:050315 appmgrd[1081]: E appmgr_lipc:lipc_set_prop_fail:lipc_status=3,app=com.github.koreader.kpvbooklet,property=load:send app command
140101:050315 appmgrd[1081]: I appmgr_lipc:default_alert_displayed:app_lipc_id=com.github.koreader.kpvbooklet:show_simple_alert
140101:050318 Xorg: I GestureEngine:perfScenario::Sending button 1 down 1388581398.303466
140101:050318 pillow[15030]: I def:button-press:target=simple_alert,button=1:
140101:050318 Xorg: I GestureEngine:perfScenario::Sending button 1 up 1388581398.458791
140101:050318 pillow[15030]: I def:button-release:target=simple_alert,button=1:
[root@kindle root]# 
```

**Comment by aerickson** [comment]
As mentioned in https://github.com/koreader/kpvbooklet/pull/38, I think I've got a too modern Java.

```
$ java --version
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by NiLuJe** [comment]
FWIW, I'm using the Oracle jdk 1.8.0.192, and I successfully rebuilt KUAL with it last week.

**Comment by NiLuJe** [comment]
There may be weird quirks depending on which FW version you're pulling the JARs from.

For non-FW specific stuff, we usually went with the earliest supported release (IIRC, for KUAL, that's FW 5.0.x or 5.1.x maybe).

**Comment by NiLuJe** [comment]
Found the [JEP](https://openjdk.java.net/jeps/182) about dropping old source/target versions ;).

**Comment by NiLuJe** [comment]
Which would imply that `1.8` is actually wrong for FW 5.x, and should be `1.4` (or something else, I've never bothered to check which exact JRE version the variant used on FW 5.x is).

In which case, see the KUAL antfile (source, target, bootclasspath).

Note that, for KUAL, I've never had issues with a bootclasspath pointing to my actual 1.8 JDK, but that may be [asking for trouble](https://blogs.oracle.com/darcy/new-javac-warning-for-setting-an-older-source-without-bootclasspath).

**Comment by NiLuJe** [comment]
I hope you're now starting to get why there isn't much documentation about building Java stuff for the Kindle: it's a mess ;D.

**Comment by NiLuJe** [comment]
[Here's where the old 1.4 JDK live](https://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase14-419411.html).

**Comment by aerickson** [comment]
Success... I had a Linux/ubuntu host with OpenJDK 1.8 and it worked. New build is at https://github.com/aerickson/kpvbooklet/releases/tag/v0.6.7.pre3.

https://github.com/koreader/kpvbooklet/pull/38 updated with java tips and the build.xml change. Not sure if the build.xml is required. It could be that using Java 8 vs Java 10 that fixed it.
